import numpy as np
from typing import Dict, List, Tuple
import gzip
import struct
from pathlib import Path

class NBTWriter:
    def __init__(self):
        self.data = bytearray()
    
    def write_byte(self, value: int):
        self.data.extend(struct.pack('>b', value))
    
    def write_short(self, value: int):
        self.data.extend(struct.pack('>h', value))
    
    def write_int(self, value: int):
        self.data.extend(struct.pack('>i', value))
    
    def write_long(self, value: int):
        self.data.extend(struct.pack('>q', value))
    
    def write_string(self, value: str):
        encoded = value.encode('utf-8')
        self.write_short(len(encoded))
        self.data.extend(encoded)
    
    def write_tag(self, tag_type: int, name: str = ""):
        self.write_byte(tag_type)
        if tag_type != 0:
            self.write_string(name)
    
    def write_compound_start(self, name: str = ""):
        self.write_tag(10, name)
    
    def write_compound_end(self):
        self.write_byte(0)
    
    def write_int_tag(self, name: str, value: int):
        self.write_tag(3, name)
        self.write_int(value)
    
    def write_long_tag(self, name: str, value: int):
        self.write_tag(4, name)
        self.write_long(value)
    
    def write_string_tag(self, name: str, value: str):
        self.write_tag(8, name)
        self.write_string(value)
    
    def write_byte_array_tag(self, name: str, value: bytes):
        self.write_tag(7, name)
        self.write_int(len(value))
        self.data.extend(value)
    
    def write_list_tag(self, name: str, tag_type: int, items: list):
        self.write_tag(9, name)
        self.write_byte(tag_type)
        self.write_int(len(items))

def export_to_litematic(
    blocks: np.ndarray,
    block_names: List[str],
    output_path: str,
    name: str = "AI Generated Build",
    author: str = "MinecraftAI",
    description: str = "Generated by AI"
):
    sx, sy, sz = blocks.shape
    
    writer = NBTWriter()
    
    writer.write_compound_start()
    
    writer.write_int_tag("Version", 6)
    writer.write_int_tag("MinecraftDataVersion", 3120)
    
    writer.write_compound_start("Metadata")
    writer.write_string_tag("Name", name)
    writer.write_string_tag("Author", author)
    writer.write_string_tag("Description", description)
    writer.write_long_tag("TimeCreated", 0)
    writer.write_long_tag("TimeModified", 0)
    writer.write_int_tag("RegionCount", 1)
    writer.write_int_tag("TotalBlocks", int(np.sum(blocks != 0)))
    writer.write_int_tag("TotalVolume", sx * sy * sz)
    
    writer.write_compound_start("EnclosingSize")
    writer.write_int_tag("x", sx)
    writer.write_int_tag("y", sy)
    writer.write_int_tag("z", sz)
    writer.write_compound_end()
    
    writer.write_compound_end()
    
    writer.write_compound_start("Regions")
    writer.write_compound_start("main")
    
    writer.write_compound_start("Position")
    writer.write_int_tag("x", 0)
    writer.write_int_tag("y", 0)
    writer.write_int_tag("z", 0)
    writer.write_compound_end()
    
    writer.write_compound_start("Size")
    writer.write_int_tag("x", sx)
    writer.write_int_tag("y", sy)
    writer.write_int_tag("z", sz)
    writer.write_compound_end()
    
    palette = []
    palette_map = {}
    
    for block_id in np.unique(blocks):
        if block_id >= len(block_names):
            continue
        block_name = block_names[block_id]
        if block_name not in palette_map:
            palette_map[block_name] = len(palette)
            palette.append(block_name)
    
    writer.write_list_tag("BlockStatePalette", 10, palette)
    for block_name in palette:
        writer.write_compound_start()
        writer.write_string_tag("Name", block_name)
        writer.write_compound_end()
    
    remapped = np.zeros_like(blocks)
    for i, block_id in enumerate(np.unique(blocks)):
        if block_id >= len(block_names):
            continue
        block_name = block_names[block_id]
        if block_name in palette_map:
            remapped[blocks == block_id] = palette_map[block_name]
    
    flat = remapped.flatten()
    
    bits_per_block = max(2, (len(palette) - 1).bit_length())
    
    blocks_per_long = 64 // bits_per_block
    num_longs = (len(flat) + blocks_per_long - 1) // blocks_per_long
    
    packed = []
    for i in range(num_longs):
        long_val = 0
        for j in range(blocks_per_long):
            idx = i * blocks_per_long + j
            if idx < len(flat):
                block_val = int(flat[idx])
                long_val |= (block_val << (j * bits_per_block))
        packed.append(long_val)
    
    packed_bytes = b''.join(struct.pack('>q', val) for val in packed)
    writer.write_byte_array_tag("BlockStates", packed_bytes)
    
    writer.write_list_tag("Entities", 10, [])
    writer.write_list_tag("TileEntities", 10, [])
    writer.write_list_tag("PendingBlockTicks", 10, [])
    writer.write_list_tag("PendingFluidTicks", 10, [])
    
    writer.write_compound_end()
    writer.write_compound_end()
    
    writer.write_compound_end()
    
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    
    with gzip.open(output_path, 'wb') as f:
        f.write(writer.data)
    
    print(f"Exported to {output_path}")
    print(f"Size: {sx}x{sy}x{sz}")
    print(f"Palette size: {len(palette)}")
    print(f"Total blocks: {int(np.sum(blocks != 0))}")
